language: python

jobs:
  include:
    - os: "linux"
      python: "2.7"
    - os: "linux"
      python: "3.5"
    - os: "linux"
      python: "3.6"
    - os: "linux"
      python: "3.7"
    - os: "linux"
      python: "3.8"
      env: "CPPFLAGS=--coverage"
    - name: "macOS"
      os: "osx"
      osx_image: "xcode11.3"
      language: "shell"
      addons:
        homebrew:
          packages:
            - pkg-config
            - poppler
            - python

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    sudo apt-get update
    sudo apt-get install --yes libpoppler-cpp-dev pkg-config
    fi

before_script:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" && $TRAVIS_PYTHON_VERSION == "3.8" ]]; then
    pip install black cpp-coveralls
    fi

script:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    python --version
    python setup.py test
    fi
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    python3 --version
    python3 setup.py test
    fi
  - |
    if [[ $TRAVIS_OS_NAME == "linux" && $TRAVIS_PYTHON_VERSION == "3.8" ]]; then
    black --check .
    fi

after_success:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" && $TRAVIS_PYTHON_VERSION == "3.8" ]]; then
    coveralls --build-root .
    fi
